name: Build Release Artifacts
on:
  release:
    types: [created]
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@13.4
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          cli: 1.10.1.693
      - run: clojure -X:uberjar
      - run: jpackage @jpackage/common @jpackage/linux
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Notebox_1.0-1_amd64.deb
          asset_name: Notebox_1.0-1_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@13.4
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          cli: 1.10.1.693
      - run: clojure -X:uberjar
      - run: jpackage @jpackage/common @jpackage/mac
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Notebox-1.0.dmg
          asset_name: Notebox-1.0.dmg
          asset_content_type: application/x-apple-diskimage
  build-dmg-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@13.4
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          cli: 1.10.1.693
      - run: clojure -X:uberjar
      - run: jpackage @jpackage/common @jpackage/mac_aarch64
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Notebox-1.0.dmg
          asset_name: Notebox-1.0.dmg
          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - run: iwr -useb download.clojure.org/install/win-install-1.10.1.536.ps1 | iex
      - run: clojure -X:uberjar
      - run: jpackage @jpackage/common @jpackage/windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Notebox-1.0.exe
          asset_name: Notebox-1.0.exe
          asset_content_type: application/vnd.microsoft.portable-executable